name: whatsapp_link_generator
description: WhatsApp link generator

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.15-F+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.12
  cupertino_icons: ^1.0.5
  auto_size_text: ^3.0.0
  # https://github.com/Idean/Flutter-Neumorphic/issues/274
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  path_provider: ^2.0.15
  share_plus: ^7.1.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
